output_dir: ./results/simclr-audioset-resnet50

dataset:
  dataset_name: AudioSetViews
  batch_size: 128
  num_workers: 16 
  configuration:
    df_path: /storage13/datasets/audioset/audios/train-full-records-hot1.pkl 
    sample_rate: 8000
    num_views: 2
    num_repeat: 2
    max_size: null
    dir_noises: /storage13/datasets/arabic-speech-corpus/wav

training:
  seed: 123
  gradient_accumulation_steps: 1
  learning_rate: 1e-4
  lr_scheduler: cosine
  lr_warmup_steps: 10
  temperature: 0.5
  num_epochs: 100
  save_every_epoch: 5
  mixed_precision: fp16
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay: 1e-4
  adam_epsilon: 1e-08
  max_grad_norm: 1.0
  scale_lr: False
  resume_from_checkpoint: null

model:
  model_name: ResNetSimCLR
  configuration:
    base_model: resnet50
    out_dim: 512
    n_fft: 510
    hop_length: 313
    normalized: False
